package ftn.is.serviceGen.nastavnik;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-12-17T00:22:09.859+01:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://service.is.ftn/", name = "NastavnikService")
@XmlSeeAlso({ObjectFactory.class})
public interface NastavnikService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPrisustva", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.GetPrisustva")
    @WebMethod
    @ResponseWrapper(localName = "getPrisustvaResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.GetPrisustvaResponse")
    public java.util.List<ftn.is.serviceGen.nastavnik.PripadnostGrupi> getPrisustva(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "removeStudentFromGroup", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.RemoveStudentFromGroup")
    @WebMethod
    @ResponseWrapper(localName = "removeStudentFromGroupResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.RemoveStudentFromGroupResponse")
    public boolean removeStudentFromGroup(
        @WebParam(name = "arg0", targetNamespace = "")
        ftn.is.serviceGen.nastavnik.Student arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        ftn.is.serviceGen.nastavnik.Grupa arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getStudentsInGroup", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.GetStudentsInGroup")
    @WebMethod
    @ResponseWrapper(localName = "getStudentsInGroupResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.GetStudentsInGroupResponse")
    public java.util.List<ftn.is.serviceGen.nastavnik.Student> getStudentsInGroup(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @RequestWrapper(localName = "setPrisustva", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.SetPrisustva")
    @WebMethod
    @ResponseWrapper(localName = "setPrisustvaResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.SetPrisustvaResponse")
    public void setPrisustva(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<ftn.is.serviceGen.nastavnik.PripadnostGrupi> arg0
    );

    @RequestWrapper(localName = "setOdslusaniPredmeti", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.SetOdslusaniPredmeti")
    @WebMethod
    @ResponseWrapper(localName = "setOdslusaniPredmetiResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.SetOdslusaniPredmetiResponse")
    public void setOdslusaniPredmeti(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<ftn.is.serviceGen.nastavnik.OdslusanPredmet> arg0
    );

    @RequestWrapper(localName = "deleteStudent", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.DeleteStudent")
    @WebMethod
    @ResponseWrapper(localName = "deleteStudentResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.DeleteStudentResponse")
    public void deleteStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        ftn.is.serviceGen.nastavnik.Student arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getGrupeForPredmet", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.GetGrupeForPredmet")
    @WebMethod
    @ResponseWrapper(localName = "getGrupeForPredmetResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.GetGrupeForPredmetResponse")
    public java.util.List<ftn.is.serviceGen.nastavnik.Grupa> getGrupeForPredmet(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @RequestWrapper(localName = "deleteObaveza", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.DeleteObaveza")
    @WebMethod
    @ResponseWrapper(localName = "deleteObavezaResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.DeleteObavezaResponse")
    public void deleteObaveza(
        @WebParam(name = "arg0", targetNamespace = "")
        ftn.is.serviceGen.nastavnik.Obaveza arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.AddStudent")
    @WebMethod
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.AddStudentResponse")
    public boolean addStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        ftn.is.serviceGen.nastavnik.Student arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getStudentsNotInGroups", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.GetStudentsNotInGroups")
    @WebMethod
    @ResponseWrapper(localName = "getStudentsNotInGroupsResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.GetStudentsNotInGroupsResponse")
    public java.util.List<ftn.is.serviceGen.nastavnik.Student> getStudentsNotInGroups(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getObaveze", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.GetObaveze")
    @WebMethod
    @ResponseWrapper(localName = "getObavezeResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.GetObavezeResponse")
    public java.util.List<ftn.is.serviceGen.nastavnik.Obaveza> getObaveze(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @RequestWrapper(localName = "addStudentToGroup", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.AddStudentToGroup")
    @WebMethod
    @ResponseWrapper(localName = "addStudentToGroupResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.AddStudentToGroupResponse")
    public void addStudentToGroup(
        @WebParam(name = "arg0", targetNamespace = "")
        ftn.is.serviceGen.nastavnik.Student arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        ftn.is.serviceGen.nastavnik.Grupa arg1
    );

    @RequestWrapper(localName = "editGrupa", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.EditGrupa")
    @WebMethod
    @ResponseWrapper(localName = "editGrupaResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.EditGrupaResponse")
    public void editGrupa(
        @WebParam(name = "arg0", targetNamespace = "")
        ftn.is.serviceGen.nastavnik.Grupa arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listStudenti", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.ListStudenti")
    @WebMethod
    @ResponseWrapper(localName = "listStudentiResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.ListStudentiResponse")
    public java.util.List<ftn.is.serviceGen.nastavnik.Student> listStudenti();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "editNastavnik", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.EditNastavnik")
    @WebMethod
    @ResponseWrapper(localName = "editNastavnikResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.EditNastavnikResponse")
    public boolean editNastavnik(
        @WebParam(name = "arg0", targetNamespace = "")
        ftn.is.serviceGen.nastavnik.Nastavnik arg0
    );

    @RequestWrapper(localName = "addGrupa", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.AddGrupa")
    @WebMethod
    @ResponseWrapper(localName = "addGrupaResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.AddGrupaResponse")
    public void addGrupa(
        @WebParam(name = "arg0", targetNamespace = "")
        ftn.is.serviceGen.nastavnik.Grupa arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getOdslusaniPredmeti", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.GetOdslusaniPredmeti")
    @WebMethod
    @ResponseWrapper(localName = "getOdslusaniPredmetiResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.GetOdslusaniPredmetiResponse")
    public java.util.List<ftn.is.serviceGen.nastavnik.OdslusanPredmet> getOdslusaniPredmeti(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getNastavnik", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.GetNastavnik")
    @WebMethod
    @ResponseWrapper(localName = "getNastavnikResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.GetNastavnikResponse")
    public ftn.is.serviceGen.nastavnik.Nastavnik getNastavnik(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @RequestWrapper(localName = "addObaveza", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.AddObaveza")
    @WebMethod
    @ResponseWrapper(localName = "addObavezaResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.AddObavezaResponse")
    public void addObaveza(
        @WebParam(name = "arg0", targetNamespace = "")
        ftn.is.serviceGen.nastavnik.Obaveza arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "editStudent", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.EditStudent")
    @WebMethod
    @ResponseWrapper(localName = "editStudentResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.EditStudentResponse")
    public boolean editStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        ftn.is.serviceGen.nastavnik.Student arg0
    );

    @RequestWrapper(localName = "deleteGrupa", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.DeleteGrupa")
    @WebMethod
    @ResponseWrapper(localName = "deleteGrupaResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.DeleteGrupaResponse")
    public void deleteGrupa(
        @WebParam(name = "arg0", targetNamespace = "")
        ftn.is.serviceGen.nastavnik.Grupa arg0
    );

    @RequestWrapper(localName = "editObaveza", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.EditObaveza")
    @WebMethod
    @ResponseWrapper(localName = "editObavezaResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.EditObavezaResponse")
    public void editObaveza(
        @WebParam(name = "arg0", targetNamespace = "")
        ftn.is.serviceGen.nastavnik.Obaveza arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPredmetiForNastavnik", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.GetPredmetiForNastavnik")
    @WebMethod
    @ResponseWrapper(localName = "getPredmetiForNastavnikResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.nastavnik.GetPredmetiForNastavnikResponse")
    public java.util.List<ftn.is.serviceGen.nastavnik.Predmet> getPredmetiForNastavnik(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
