package ftn.is.serviceGen.administrator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-02-03T16:18:37.750+01:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://service.is.ftn/", name = "AdminService")
@XmlSeeAlso({ObjectFactory.class})
public interface AdminService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "restore", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.Restore")
    @WebMethod
    @ResponseWrapper(localName = "restoreResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.RestoreResponse")
    public boolean restore(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0
    );

    @RequestWrapper(localName = "editPredmet", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.EditPredmet")
    @WebMethod
    @ResponseWrapper(localName = "editPredmetResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.EditPredmetResponse")
    public void editPredmet(
        @WebParam(name = "arg0", targetNamespace = "")
        ftn.is.serviceGen.administrator.Predmet arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "backup", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.Backup")
    @WebMethod
    @ResponseWrapper(localName = "backupResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.BackupResponse")
    public byte[] backup();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listOdseci", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.ListOdseci")
    @WebMethod
    @ResponseWrapper(localName = "listOdseciResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.ListOdseciResponse")
    public java.util.List<ftn.is.serviceGen.administrator.Odsek> listOdseci();

    @RequestWrapper(localName = "addPredmet", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.AddPredmet")
    @WebMethod
    @ResponseWrapper(localName = "addPredmetResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.AddPredmetResponse")
    public void addPredmet(
        @WebParam(name = "arg0", targetNamespace = "")
        ftn.is.serviceGen.administrator.Predmet arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listNastavnici", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.ListNastavnici")
    @WebMethod
    @ResponseWrapper(localName = "listNastavniciResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.ListNastavniciResponse")
    public java.util.List<ftn.is.serviceGen.administrator.Nastavnik> listNastavnici();

    @RequestWrapper(localName = "deletePredmet", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.DeletePredmet")
    @WebMethod
    @ResponseWrapper(localName = "deletePredmetResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.DeletePredmetResponse")
    public void deletePredmet(
        @WebParam(name = "arg0", targetNamespace = "")
        ftn.is.serviceGen.administrator.Predmet arg0
    );

    @RequestWrapper(localName = "editOdsek", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.EditOdsek")
    @WebMethod
    @ResponseWrapper(localName = "editOdsekResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.EditOdsekResponse")
    public void editOdsek(
        @WebParam(name = "arg0", targetNamespace = "")
        ftn.is.serviceGen.administrator.Odsek arg0
    );

    @RequestWrapper(localName = "editNastavnik", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.EditNastavnik")
    @WebMethod
    @ResponseWrapper(localName = "editNastavnikResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.EditNastavnikResponse")
    public void editNastavnik(
        @WebParam(name = "arg0", targetNamespace = "")
        ftn.is.serviceGen.administrator.Nastavnik arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAdmin", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.GetAdmin")
    @WebMethod
    @ResponseWrapper(localName = "getAdminResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.GetAdminResponse")
    public ftn.is.serviceGen.administrator.Administrator getAdmin(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @RequestWrapper(localName = "addOdsek", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.AddOdsek")
    @WebMethod
    @ResponseWrapper(localName = "addOdsekResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.AddOdsekResponse")
    public void addOdsek(
        @WebParam(name = "arg0", targetNamespace = "")
        ftn.is.serviceGen.administrator.Odsek arg0
    );

    @RequestWrapper(localName = "addNastavnik", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.AddNastavnik")
    @WebMethod
    @ResponseWrapper(localName = "addNastavnikResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.AddNastavnikResponse")
    public void addNastavnik(
        @WebParam(name = "arg0", targetNamespace = "")
        ftn.is.serviceGen.administrator.Nastavnik arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "editAdministrator", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.EditAdministrator")
    @WebMethod
    @ResponseWrapper(localName = "editAdministratorResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.EditAdministratorResponse")
    public boolean editAdministrator(
        @WebParam(name = "arg0", targetNamespace = "")
        ftn.is.serviceGen.administrator.Administrator arg0
    );

    @RequestWrapper(localName = "deleteNastavnik", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.DeleteNastavnik")
    @WebMethod
    @ResponseWrapper(localName = "deleteNastavnikResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.DeleteNastavnikResponse")
    public void deleteNastavnik(
        @WebParam(name = "arg0", targetNamespace = "")
        ftn.is.serviceGen.administrator.Nastavnik arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listPredmeti", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.ListPredmeti")
    @WebMethod
    @ResponseWrapper(localName = "listPredmetiResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.ListPredmetiResponse")
    public java.util.List<ftn.is.serviceGen.administrator.Predmet> listPredmeti();

    @RequestWrapper(localName = "deleteOdsek", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.DeleteOdsek")
    @WebMethod
    @ResponseWrapper(localName = "deleteOdsekResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.administrator.DeleteOdsekResponse")
    public void deleteOdsek(
        @WebParam(name = "arg0", targetNamespace = "")
        ftn.is.serviceGen.administrator.Odsek arg0
    );
}
