package ftn.is.serviceGen.administrator;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2013-02-03T16:18:38.015+01:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "AdminServiceService", 
                  wsdlLocation = "http://localhost:80/ftn-is-ejb-1.0/AdminService?wsdl",
                  targetNamespace = "http://service.is.ftn/") 
public class AdminServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.is.ftn/", "AdminServiceService");
    public final static QName AdminServicePort = new QName("http://service.is.ftn/", "AdminServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:80/ftn-is-ejb-1.0/AdminService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AdminServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:80/ftn-is-ejb-1.0/AdminService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AdminServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AdminServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdminServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AdminServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AdminServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AdminServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AdminService
     */
    @WebEndpoint(name = "AdminServicePort")
    public AdminService getAdminServicePort() {
        return super.getPort(AdminServicePort, AdminService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdminService
     */
    @WebEndpoint(name = "AdminServicePort")
    public AdminService getAdminServicePort(WebServiceFeature... features) {
        return super.getPort(AdminServicePort, AdminService.class, features);
    }

}
