package ftn.is.serviceGen.student;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-12-19T23:57:21.046+01:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://service.is.ftn/", name = "StudentService")
@XmlSeeAlso({ObjectFactory.class})
public interface StudentService {

    @RequestWrapper(localName = "prijavaIspita", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.student.PrijavaIspita")
    @WebMethod
    @ResponseWrapper(localName = "prijavaIspitaResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.student.PrijavaIspitaResponse")
    public void prijavaIspita(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<ftn.is.serviceGen.student.PrijavljenIspit> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getStudent", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.student.GetStudent")
    @WebMethod
    @ResponseWrapper(localName = "getStudentResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.student.GetStudentResponse")
    public ftn.is.serviceGen.student.Student getStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listaPrijavljenihIspita", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.student.ListaPrijavljenihIspita")
    @WebMethod
    @ResponseWrapper(localName = "listaPrijavljenihIspitaResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.student.ListaPrijavljenihIspitaResponse")
    public java.util.List<ftn.is.serviceGen.student.PrijavljenIspit> listaPrijavljenihIspita(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @RequestWrapper(localName = "editLozinka", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.student.EditLozinka")
    @WebMethod
    @ResponseWrapper(localName = "editLozinkaResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.student.EditLozinkaResponse")
    public void editLozinka(
        @WebParam(name = "arg0", targetNamespace = "")
        ftn.is.serviceGen.student.Student arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listaPredmetaZaPrijavu", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.student.ListaPredmetaZaPrijavu")
    @WebMethod
    @ResponseWrapper(localName = "listaPredmetaZaPrijavuResponse", targetNamespace = "http://service.is.ftn/", className = "ftn.is.serviceGen.student.ListaPredmetaZaPrijavuResponse")
    public java.util.List<ftn.is.serviceGen.student.Predmet> listaPredmetaZaPrijavu(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
