package ftn.is.serviceGen.student;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import javax.jws.HandlerChain;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-12-19T23:57:21.375+01:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "StudentServiceService", 
                  wsdlLocation = "http://localhost:80/ftn-is-ejb-1.0/StudentService?wsdl",
                  targetNamespace = "http://service.is.ftn/") 
@HandlerChain(file="/handler-chain.xml")
public class StudentServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.is.ftn/", "StudentServiceService");
    public final static QName StudentServicePort = new QName("http://service.is.ftn/", "StudentServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:80/ftn-is-ejb-1.0/StudentService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StudentServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:80/ftn-is-ejb-1.0/StudentService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StudentServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StudentServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StudentServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StudentServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StudentServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns StudentService
     */
    @WebEndpoint(name = "StudentServicePort")
    public StudentService getStudentServicePort() {
        return super.getPort(StudentServicePort, StudentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentService
     */
    @WebEndpoint(name = "StudentServicePort")
    public StudentService getStudentServicePort(WebServiceFeature... features) {
        return super.getPort(StudentServicePort, StudentService.class, features);
    }

}
